import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :web_interface, WebInterfaceWeb.Endpoint,
  http: [port: 80],
  url: [host: "localhost", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :auction_house,
  api_search_url: "https://api.warframe.market/v1/items",
  api_base_url: "https://api.warframe.market/v1/profile/orders",
  auction_house_cookie: System.fetch_env!("MARKET_MANAGER_WM_COOKIE"),
  auction_house_token: System.fetch_env!("MARKET_MANAGER_WM_XCSRFTOKEN")

config :store,
  products: "products.json",
  current_orders: "current_orders.json",
  setup: "setup.json"
