import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :web_interface, WebInterface.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: "CCUaDp4htK08p5Uusqp5qUVBriyxaFqqREJeviYYArsfVXMsciGMv+ybS1A2rNoL",
  check_origin: false,
  server: true

config :store,
  products: ["priv", "products.json"],
  watch_list: ["priv", "watch_list.json"],
  setup: ["priv", "setup.json"],
  syndicates: ["priv", "syndicates.json"]

config :auction_house,
  api_item_orders_url: "https://api.warframe.market/v2/orders/item",
  api_order_url: "https://api.warframe.market/v2/order",
  market_signin_url: "https://warframe.market/auth/signin",
  api_signin_url: "https://api.warframe.market/v1/auth/signin",
  api_user_orders_url: "https://api.warframe.market/v2/orders/user"

config :rate_limiter,
  algorithm: RateLimiter.LeakyBucket,
  requests_per_second: 1
