name: build

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # build:
  #   name: Build on Windows
  #   runs-on: windows-2019

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: erlef/setup-beam@v1
  #     with:
  #       elixir-version: '1.13.x' # Define the elixir version [required]
  #       otp-version: '24.2.x' # Define the OTP version [required]
    
  #   - name: Install choco
  #     shell: powershell
  #     run: |
  #       Set-ExecutionPolicy -ExecutionPolicy Bypass
  #       Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

  #   - name: Install bakeware dependencies
  #     shell: powershell
  #     run: choco install -y zstandard make mingw

  #   - name: Install Dependencies
  #     run: |
  #       mix local.hex --force
  #       mix local.rebar --force
  #       mix deps.get

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir_version }}
          otp-version: ${{ matrix.otp_version }}
      - name: Restore deps and _build
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Restore plts
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: ${{ runner.os }}-dialyzer-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix deps.get
      - run: MIX_ENV=test mix compile --warnings-as-errors
      - run: mix test
      - name: Extra checks
        run: |
          mix dialyzer --halt-exit-status

windows:
    name: Test on Windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.x' # Define the elixir version [required]
          otp-version: '24.2.x' # Define the OTP version [required]

      - name: Compile (PowerShell)
        run: mix compile --warnings-as-errors
        env:
          MAKE: make
          CC: gcc
      - name: Test (PowerShell)
        run: mix test
        env:
          MAKE: make
          CC: gcc
