name: build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on Windows
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16.x'  # Define the elixir version [required]
        otp-version: '26.2.x'     # Define the OTP version [required]

    - name: Run Tests
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix test
      env:
        MIX_ENV: test

    # - name: Run Coverage
    #   run: |
    #     mix local.hex --force
    #     mix local.rebar --force
    #     mix deps.get  
    #     mix coveralls.github
    #   env:
    #     MIX_ENV: test
    
    - name: Run Credo
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get  
        mix credo --strict
      env:
        MIX_ENV: dev

    - name: Run Dialyzer
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get  
        mix dialyzer
      env:
        MIX_ENV: dev

    - name: Build executable
      run: mix release
      env:
        MIX_ENV: prod