name: build

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on Windows
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.13.x'  # Define the elixir version [required]
        otp-version: '24.2.x'     # Define the OTP version [required]
    
    - name: Install choco
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    
    - name: Install bakeware dependencies
      shell: powershell
      run: choco install -y zstandard make

    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
    
    - name: Compile project
      run: |
        mix deps.compile
        mix compile
      env:
        MAKE: make
        CC: gcc

    - name: Run Tests
      run: mix test
      env:
        MAKE: make
        CC: gcc

    - name: Run Coverage
      run: mix coveralls.github
      env:
        MAKE: make
        CC: gcc
    
    - name: Run credo code analyser
      run: mix credo --strict
      env:
        MAKE: make
        CC: gcc
    
    - name: Run typechecks
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{ runner.os }}-dialyzer-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      run: mix dialyzer
      env:
        MAKE: make
        CC: gcc
    
    - name: Build executable
      run: mix release
      env:
        MAKE: make
        CC: gcc
        MIX_ENV: prod